### ISSUE TITLE
different sites do not connect

### ISSUE THREAD

**Issue by Ben9000** [lloc/Multisite-Language-Switcher#119]
I set up the plugin like it says in the documentation: http://msls.co/install-config-and-use/
Two sites in a multisite installation.
But I still get the following error when entering a post on either site:
You should define at least another blog in a different language in order to have some benefit from this plugin!

What can I do here? Both sides should see each other when the plugin is network activated and in both sites I entered the language under "Settings" > "Multisite-Language-Switcher", right?

**Comment by vitaliy-spb** [comment]
Yes, i can have same problem
Any solutions?

**Comment by lloc** [comment]
The plugin recognizes the connection of sites by getting the sites from a specific user. That is the reason why I inserted the option for a reference user. MSLS cannot find a connection if you use two different users. I just guess that could be the problem.

**Comment by florianbrinkmann** [comment]
Hi @lloc,

thanks for the plugin!

I just add the comment here instead of opening a new issue, it is more a question regarding the reference user thing and it think it fits in the issue here.

Why does that setting exist? Is it not possible to get the site connections without a user? Background of the question is, that I created a custom frontend language menu with your code snippet (http://msls.co/developer-docs/snippets-examples.html#the-blog-collection) as a starting point, and when a wrong user is set as a reference user, it does not work, and for me it seems like an easy point of accidentially error.

Thanks in advance!
Florian

**Comment by lloc** [comment]
Hi @florianbrinkmann,

I did almost oversee your comment. Thanks for this!

There were some requests for creating a panel where you can connect websites. I never had the time to start this. Right now the plugin connects the websites with the get_blogs_of_user-functionality from the WordPress-API. In the past I created the reference-user since the current user were ofteh a limitation...

**Comment by florianbrinkmann** [comment]
Hi @lloc,

okay, thanks for the explanation! :)

Best,
Florian
