### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by mohansocialbeat** [lloc/Multisite-Language-Switcher#127]
Fatal error: Uncaught Error: Class 'lloc\Msls\MslsPlugin' not found in C:\xampp\htdocs\iec\wp-content\plugins\Multisite-Language-Switcher-master\MultisiteLanguageSwitcher.php:49 Stack trace: #0 C:\xampp\htdocs\iec\wp-admin\includes\plugin.php(1909): include() #1 C:\xampp\htdocs\iec\wp-admin\plugins.php(172): plugin_sandbox_scrape('Multisite-Langu...') #2 {main} thrown in C:\xampp\htdocs\iec\wp-content\plugins\Multisite-Language-Switcher-master\MultisiteLanguageSwitcher.php on line 49

**Comment by lloc** [comment]
Time for issue templates ... I created on:

**Describe the bug**
Fatal error: Uncaught Error: Class 'lloc\Msls\MslsPlugin'...

**Environment (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - PHP Version [e.g. 7.2]
- Plugin Version [e.g. 2.2.0]

**Additional context**
Add any other context about the problem here.

**Comment by lloc** [comment]
No answer here so I just guess and close the issue:

You downloaded probably the plugin from here and forget to run `composer install --no-dev`
