### ISSUE TITLE
Not working for WooCommerce product

### ISSUE THREAD

**Issue by Stock-Webdesign** [lloc/Multisite-Language-Switcher#55]
I can link my English product post to the German one but the language switcher does not link to it on the front end. It links to German home instead.

**Comment by brocheafoin** [comment]
I'm seeing the same problem with WooCommerce's custom taxonomies. WooCommerce now uses custom rewrite rules which the user can define in Settings > Permalinks. If I set a different "Product Category Base" for each site, then MSLS generates links that pick the right slug for the translation but the rewrite rules from the current site.

### Example
#### Product Category Bases
_en_US:_ product-category
_fr_FR:_ categorie-produit
#### Product Category
_en_US:_ bicycles
_fr_FR:_ velos

The fr_FR link generated on `/product-category/bicycles/` is `/product-category/velos/` instead of `/categorie-produit/velos/`

The filter mentioned in the workaround above is not called in MslsOptionsTax->get_postlink(), so there is no way to alter the URL. 

In any case, URLs should be built with the rewrite rules from the corresponding blog/language. I've taken a crack at it but have not gotten it to work yet. I'm _not_ familiar with WP_Rewrite, unfortunately...

**Comment by lloc** [comment]
Interesting! I will look into this very soon...

**Comment by Rogi842** [comment]
Hi Dennis,
I would like to ask whether a solution/workaround has been found already for the problem mentioned by last commenter, brocheafoin (commented on 5 Feb 2015 ) ?
Also, probably superfluously but anyway, the problem in my case in detail below;

I have 2 Wordpress websites with each their own domain and configured for Wordpress multisite, with MU-domain-mapping succesfully installed.
Furthermore, I have Woocommerce and Multisite Language Switcher installed and they work excellently together, except with 'product categories'.

site 1:   degoudeneeuw.eu
site 2:   thegoldenage.nl

Explanation of problem;
when I go to thegoldenage.nl -->  Jewellery  -->  Brooches  -->  Design Brooches
and then click on Country Flag: the Netherlands (above American Flag), I get:  'Die pagina kon niet gevonden worden'  (= page not found)    ERROR 404.

the url of the english(US) page;
http://thegoldenage.nl/product-category/jewellery/brooches/design-brooches/
the url of the error page (Netherlands language);
http://degoudeneeuw.eu/product-category/sieraden/broches/design-broches/
**Note:** the correct url should be with categor**ie** instead of categor**y**
(correct: http://degoudeneeuw.eu/product-categorie/sieraden/broches/design-broches/)

Can you give any advice or solution for the problem ?
Thanks in advance

**Comment by lloc** [comment]
I'm going to close this in favour of: https://github.com/lloc/Multisite-Language-Switcher/issues/399
